In [2]:
import numpy as np
from numpy.linalg import inv, det, eig, qr

A=[[0, 2],[2, 3]]
v =[1, 2]
np.dot(A,v)

array([4, 8])

In [ ]:
A = [[0, -1, 0],
     [4, 0, 2],
     [8, -1, 7]]

B = [[2], [-3], [1]]
     #[-3, 1]]
     #[1, 10]]
print(np.stack(A))
print(np.stack(B))
np.dot(A, B)

In [ ]:
import matplotlib.pyplot as plt

plt.style.use('seaborn-poster')

%matplotlib inline

def plot_vect(x, b, xlim, ylim):
    '''
    function to plot two vectors, 
    x - the original vector
    b - the transformed vector
    xlim - the limit for x
    ylim - the limit for y
    '''
    plt.figure(figsize = (10, 6))
    plt.quiver(0,0,x[0],x[1],\
        color='k',angles='xy',\
        scale_units='xy',scale=1,\
        label='Original vector')
    plt.quiver(0,0,b[0],b[1],\
        color='g',angles='xy',\
        scale_units='xy',scale=1,\
        label ='Transformed vector')
    plt.xlim(xlim)
    plt.ylim(ylim)
    plt.xlabel('X')
    plt.ylabel('Y')
    plt.legend()
    plt.show()

    
A = np.array([[2, 0],[0, 1]])
x0 = np.array([[1],[1]])
b0 = np.dot(A, x0)

plot_vect(x0,b0,(0,3),(0,2))






In [29]:
x1 = np.array([[1], [0]])
b1 = np.dot(A, x1)

plot_vect(x1,b1,(0,3),(-0.3,0.3))

NameError: name 'plot_vect' is not defined

In [30]:
x3 = np.array([[4, 1]])
np.abs(x3).max()
x3 / x3.max()

array([[1.  , 0.25]])

In [28]:
def normalize(x):
    fac = abs(x).max()
    x_n = x / x.max()
    return fac, x_n

def two_norm(x):
    two_norm = 0
    for i in x:
        two_norm += np.abs(i)**2
    two_norm = np.sqrt(two_norm)
    return two_norm

x = np.array([1, 1])
a = np.array([[3, 2], 
              [5, 3]])
tol = 0.00001
count, xn = 0, 0
diff = 1
#for i in range(8):
while diff > tol:
    _, xn = normalize(x)
    x = np.dot(a, x)
    lambda_1, x = normalize(x)
    diff = np.abs(np.sum(xn) - np.sum(x))
    count += 1
xn = two_norm(x)
xn = 1/xn
print(xn)
print(f'Eigenvalue: {np.round(lambda_1, 5)}')
print(f'Eigenvector: {np.round(np.dot(xn,x), 5)}')
print(f'Number of iterations: {count}')

0.8451542024363766
Eigenvalue: 6.16225
Eigenvector: [0.53452 0.84515]
Number of iterations: 4


In [32]:
def normalize(x):
    fac = abs(x).max()
    x_n = x / x.max()
    return fac, x_n

def two_norm(x):
    two_norm = 0
    for i in x:
        two_norm += np.abs(i)**2
    two_norm = np.sqrt(two_norm)
    return two_norm

x = np.array([1, 1])
a = np.array([[3, 2], 
              [5, 3]])
tol = 0.00001
a_inv = inv(a)

count, xn = 0, 0
diff = 1
while diff < tol:
#for i in range(11):
    _, xn = normalize(x) # for tolerance
    x = np.dot(x, a_inv)
    lambda_1, x = normalize(x)
    diff =np.abs( _ - lambda_1)
    count += 1
print(lambda_1)
print(f'Eigenvalue: {np.round(-lambda_1, 5)}')
print(f'Eigenvector: {np.round(x, 5)}')
print(f'Number of iterations: {count}')

6.162277660168377
Eigenvalue: -6.16228
Eigenvector: [1 1]
Number of iterations: 0


In [5]:
a_eiv = np.array([[3, 2], 
                  [5, 3]])
w, v = eig(a_eiv)
print(f'Eigenvalue: {w}')
print('Eigenvector:')
print(np.stack(v))

Eigenvalue: [ 6.16227766 -0.16227766]
Eigenvector:
[[ 0.53452248 -0.53452248]
 [ 0.84515425  0.84515425]]


In [50]:
a = np.array([[0, 2], 
              [2, 3]])

q, r = qr(a)

print('Q:', q)
print('R:', r)

b = np.dot(q, r)
print('QR:', b, '\n')

p = [1, 5, 10, 20]
for i in range(20):
    q, r = qr(a)
    a = np.dot(r, q)
    if i+1 in p:
        print(f'Iteration {i+1}:')
        print(a, '\n')

Q: [[ 0. -1.]
 [-1.  0.]]
R: [[-2. -3.]
 [ 0. -2.]]
QR: [[0. 2.]
 [2. 3.]] 

Iteration 1:
[[3. 2.]
 [2. 0.]] 

Iteration 5:
[[ 3.99998093  0.00976559]
 [ 0.00976559 -0.99998093]] 

Iteration 10:
[[ 4.00000000e+00  9.53674316e-06]
 [ 9.53674316e-06 -1.00000000e+00]] 

Iteration 20:
[[ 4.00000000e+00  9.09482285e-12]
 [ 9.09494702e-12 -1.00000000e+00]] 



In [52]:
a_eiv = np.array([[2, 2, 4], 
                  [1, 3, 5],
                  [2, 3, 4]])
w, v = eig(a_eiv)
print(f'Eigenvalue: {w}')
print('Eigenvector:')
print(np.stack(v))

Eigenvalue: [ 8.80916362  0.92620912 -0.73537273]
Eigenvector:
[[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]
