In [1]:
import numpy as np

def main():

    x = np.random.randint(-5, 10, 10)

    print(x)

    p = 9

    c = (np.sum(np.abs(x) ** p) ** (1. / p))
    print(c)
    b = (np.linalg.norm(x, p))
    print(b)
    d = (np.linalg.norm(x, np.inf))
   
    print(d)
    print(c == d)
if __name__ == "__main__":
    
    main()


[-3  2  1 -3  2  5  1  5 -3  8]
8.025929215717877
8.025929215717877
8.0
False


In [11]:
import numpy as np
from numpy.linalg import norm
vector_row = np.array([[10, 10]])
vector_column = np.array([[4], 
                          [4], 
                          [4], 
                          [4],
                          [4]])
print(vector_row, vector_row.shape)
print(vector_column, vector_column.shape)
#print(np.dot(vector_row, vector_column))
print(np.dot(vector_column, vector_row ))
print(norm(vector_column))
np.sqrt(4**2 + 4**2)
print(np.cross(vector_column,vector_row))

[[10 10]] (1, 2)
[[4]
 [4]
 [4]
 [4]
 [4]] (5, 1)
[[40 40]
 [40 40]
 [40 40]
 [40 40]
 [40 40]]
8.94427190999916


ValueError: incompatible dimensions for cross product
(dimension must be 2 or 3)

In [147]:
from numpy.linalg import norm
new_vector = vector_row.T
print(new_vector)
norm_1 = norm(new_vector, 1)
norm_2 = norm(new_vector, 2)
norm_inf = norm(new_vector, np.inf)
print('L_1 is: %.1f'%norm_1)
print('L_2 is: %.1f'%norm_2)
print('L_inf is: %.1f'%norm_inf)
a = np.array([[1], [0.001]])
b = np.array([[0.001], [1]])
norm(a) - norm(b)

[[ 1]
 [12]
 [13]
 [ 4]]
L_1 is: 30.0
L_2 is: 18.2
L_inf is: 13.0


0.0

In [73]:
a = 10
print('scalar = ', a)
v = np.array([4, 5, 6, 7, 8, 9])
print('v:', v)
v1 = np.multiply(a, v)
print('v1:', v1)
w = np.array([1, 2, 3, 4, 5, 6])
print('w:', w)
w1 = np.multiply(a, w)
print('w1:', w1)
v1w1 = np.add(v1, w1)
print('av + aw = ', v1w1)
v2w2 = np.multiply(a, np.add(v, w))
print('a(v + w) = ', v2w2)
if np.sum(v1w1) == np.sum(v2w2):
    ans = 'Yes'
print('Is a(v + w) = av + aw ? ', ans)

scalar =  10
v: [4 5 6 7 8 9]
v1: [40 50 60 70 80 90]
w: [1 2 3 4 5 6]
w1: [10 20 30 40 50 60]
av + aw =  [ 50  70  90 110 130 150]
a(v + w) =  [ 50  70  90 110 130 150]
Is a(v + w) = av + aw ?  Yes


In [149]:
from numpy import arccos, dot

v = np.array([[1, 0.001]])
print(v, 'norm :', norm(v, 2))
w = np.array([[0.001, 1]])
print(w, 'norm :', norm(w, 2))
print('transposed w\n ', w.T)
print('v · w.T = ', dot(v, w.T))
theta = \
    arccos(dot(v, w.T)/(norm(v)*norm(w)))
print('∅ = cos^-1[(v · w.T)/(|v||w|)] = ', theta)

[[1.    0.001]] norm : 1.000000499999875
[[0.001 1.   ]] norm : 1.000000499999875
transposed w
  [[0.001]
 [1.   ]]
v · w.T =  [[0.002]]
∅ = cos^-1[(v · w.T)/(|v||w|)] =  [[1.56879633]]


In [82]:
v = np.array([[0, 2, 0]])
w = np.array([[3, 0, 0]])
print(np.cross(v, w))

[[ 0  0 -6]]


In [155]:
P = np.array([[1, 7],
              [2, 3],
              [5, 0]])
Q = np.array([[2, 6, 3, 1],
              [1, 2, 3, 4]])
print(P,'\n', P.shape)
print(Q, '\n', Q.shape)
print(np.dot(P, Q))
np.dot(Q, P)

[[1 7]
 [2 3]
 [5 0]] 
 (3, 2)
[[2 6 3 1]
 [1 2 3 4]] 
 (2, 4)
[[ 9 20 24 29]
 [ 7 18 15 14]
 [10 30 15  5]]


ValueError: shapes (2,4) and (3,2) not aligned: 4 (dim 1) != 3 (dim 0)

In [156]:
from numpy.linalg import det

M = np.array([[0,1,1,3], 
             [1,2,7,1], 
             [1,0,7,3],
             [0,5,2,1]])
print('M:\n', M)

print('Determinant: %.3f'%det(M))
I = np.eye(4)
print('I:\n', I)
print('M*I:\n', np.dot(M, I))

M:
 [[0 1 1 3]
 [1 2 7 1]
 [1 0 7 3]
 [0 5 2 1]]
Determinant: 4.000
I:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
M*I:
 [[0. 1. 1. 3.]
 [1. 2. 7. 1.]
 [1. 0. 7. 3.]
 [0. 5. 2. 1.]]


In [157]:
from numpy.linalg import inv, matrix_rank, cond, multi_dot
print('M:\n', M)
print('Inv M:\n', inv(M))
print('det of Inv M:\n', det(inv(M)))
P = np.array([[0,1,0],
              [0,1,0],
              [1,0,1]])
print('P:\n', P)
# print('Inv P:\n', inv(P))
print('det(P):\n', det(P))

M:
 [[0 1 1 3]
 [1 2 7 1]
 [1 0 7 3]
 [0 5 2 1]]
Inv M:
 [[ 18.    22.25 -21.25 -12.5 ]
 [  1.     1.25  -1.25  -0.5 ]
 [ -3.    -3.5    3.5    2.  ]
 [  1.     0.75  -0.75  -0.5 ]]
det of Inv M:
 0.25
P:
 [[0 1 0]
 [0 1 0]
 [1 0 1]]
det(P):
 0.0


In [116]:
N = [[0, 3, 2],
     [4, 1, 1],
     [8, 2, 2]]
print('Original Matrix:\n', np.matrix(N))
print('rank:\n', matrix_rank(N))
print('Condition Number:\n', cond(N))
y = [[1], [4], [3]]
N_y = np.concatenate((N, y), axis = 1)
print('Augmented matrix:\n', N_y)
print('Rank:\n', matrix_rank(N_y))

Original Matrix:
 [[0 3 2]
 [4 1 1]
 [8 2 2]]
rank:
 2
Condition Number:
 7.830072952918736e+16
Augmented matrix:
 [[0 3 2 1]
 [4 1 1 4]
 [8 2 2 3]]
Rank:
 3


In [113]:
A = np.array([[1,1,0],
              [0,1,0],
              [1,0,1]])

print('Condition number:\n', cond(A))
print('Rank:\n', matrix_rank(A))
y = np.array([[1], [2], [1]])
A_y = np.concatenate((A, y), axis = 1)
print('Augmented matrix:\n', A_y)
print('Rank:\n', matrix_rank(A_y))

Condition number:
 4.048917339522305
Rank:
 3
Augmented matrix:
 [[1 1 0 1]
 [0 1 0 2]
 [1 0 1 1]]
Rank:
 3


In [188]:
M, N = 3, 4
matrix = np.arange(M*N).reshape((M,N))
print('martix:\n', matrix)
points = np.mgrid[0:N, 0:M].reshape((2, M*N))
# same method to get points
# x, y = np.mgrid[0:N, 0:M]
# points = np.vstack([x.ravel(), y.ravel()])
print(f'P or points:\n({points})')
a = np.array([[2, 2],
              [1, 0]])
print(f'a matrix:\n {a}')
new_points = np.linalg.inv(a).dot(points).astype(int)
print(f"P' or new points:\n{new_points}")
x, y = new_points.reshape((2, M, N), order='F')
print(f'x:\n{x}')
print(f'y:\n{y}')
print(f'N:\n{N}')
print(f'Nx + y:\n{N*x + y}')

martix:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
P or points:
([[0 0 0 1 1 1 2 2 2 3 3 3]
 [0 1 2 0 1 2 0 1 2 0 1 2]])
a matrix:
 [[2 2]
 [1 0]]
P' or new points:
[[ 0  1  2  0  1  2  0  1  2  0  1  2]
 [ 0 -1 -2  0  0 -1  1  0 -1  1  0  0]]
x:
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]]
y:
[[ 0  0  1  1]
 [-1  0  0  0]
 [-2 -1 -1  0]]
N:
4
Nx + y:
[[0 0 1 1]
 [3 4 4 4]
 [6 7 7 8]]


In [171]:
y

array([[0, 0, 0, 0],
       [1, 1, 1, 1],
       [2, 2, 2, 2]])

In [152]:
new

array([[ 8464, 18816, 35912],
       [ 2116,  9408, 17956],
       [16928,  6272, 26934]])

In [195]:
A = np.array([[1, 7, 2],
              [3, 5, 0]])
x = [10,
    5,
    -3]
Ta = np.dot(A,x)
Ta

array([39, 55])

In [213]:
k = 2
p = 3
x1 = [1, 0, 1]
x2 = [1, 2, 1]
newv = (np.multiply(k, x1) + np.multiply(p, x2))
print([newv[0] + newv[1], newv[0] - newv[2]])
print(np.multiply(k, [x1[0] + x1[1], x1[0] -x1[2]]) + np.multiply(p, [x2[0] + x2[1], x2[0] -x2[2]]))

[11, 0]
[11  0]


In [91]:
A = [[8, 3, -3],
    [-2, -8, 5],
    [3, 5, 10]]
x = [14, 5, -8]
x1 = 0
x2 = 0
x3 = 0
epsilon = 0.000001
converged = False

x_old = np.array([x1, x2, x3])

print('Iteration results')
print(' k,    x1,    x2,    x3 ')
for k in range(1, 50):
    x1 = (14-3*x2+3*x3)/8
    x2 = (5+2*x1-5*x3)/(-8)
    x3 = (-8-3*x1-5*x2)/(10)
    x = np.array([x1, x2, x3])
    # check if it is smaller than threshold
    dx = np.sqrt(np.dot(x-x_old, x-x_old))
    
    print("%d, %.4f, %.4f, %.4f"%(k, x1, x2, x3))
    if dx < epsilon:
        converged = True
        print('Converged!')
        break
        
    # assign the latest x value to the old value
    x_old = x

if not converged:
    print('Not converge, increase the # of iterations')

Iteration results
 k,    x1,    x2,    x3 
1, 1.7500, -1.0625, -0.7937
2, 1.8508, -1.5838, -0.5633
3, 2.1327, -1.5103, -0.6847
4, 2.0596, -1.5678, -0.6340
5, 2.1002, -1.5463, -0.6569
6, 2.0835, -1.5565, -0.6468
7, 2.0911, -1.5520, -0.6513
8, 2.0878, -1.5540, -0.6493
9, 2.0893, -1.5531, -0.6502
10, 2.0886, -1.5535, -0.6498
11, 2.0889, -1.5534, -0.6500
12, 2.0888, -1.5534, -0.6499
13, 2.0888, -1.5534, -0.6499
14, 2.0888, -1.5534, -0.6499
15, 2.0888, -1.5534, -0.6499
16, 2.0888, -1.5534, -0.6499
17, 2.0888, -1.5534, -0.6499
18, 2.0888, -1.5534, -0.6499
19, 2.0888, -1.5534, -0.6499
Converged!


In [95]:
import numpy as np
from numpy.linalg import inv, matrix_rank, cond, multi_dot, lstsq
text=np.set_printoptions(suppress=True)
A = [[8, 3, -3],
    [-2, -8, 5],
    [3, 5, 10]]
v = [14, 5, -8]

print(np.vstack(A))
diag = np.diag(np.abs(A))
off_diag = np.sum(np.abs(A), axis=1) -diag
if np.all(diag> off_diag):
    print('matrix is diagonally dominant')
else:
    print('NOT diagonally dominant')
syb = ['x = ', 'y = ','z = ']
invA = inv(A)
print('inv', np.vstack(invA))
sol = np.dot(inv(A), v)
sol2 = np.linalg.solve(A, v)

sol4 = [x1, x2, x3]

print(f'solution is {sol}')
print('ck',np.dot(A,sol))
print(f'numpy solve solution is {sol2}')
print('ck',np.matmul(A,sol2))

print(f'Gauss-Seidel solution is {sol4}')
print('ck',np.matmul(A,sol4).round(2))


[[ 8  3 -3]
 [-2 -8  5]
 [ 3  5 10]]
matrix is diagonally dominant
inv [[ 0.13513514  0.05791506  0.01158301]
 [-0.04504505 -0.11454311  0.04375804]
 [-0.01801802  0.03989704  0.07464607]]
solution is [ 2.08880309 -1.55341055 -0.64993565]
ck [14.  5. -8.]
numpy solve solution is [ 2.08880309 -1.55341055 -0.64993565]
ck [14.  5. -8.]
Gauss-Seidel solution is [2.088803221384631, -1.5534104754952236, -0.6499357286677776]
ck [14.  5. -8.]


In [103]:
C = [[ 4,  3, -5],
     [-2, -4,  5],
     [ 8,  8,  0] ]

v =  [ 2,  5, -3]
x =  ['x1', 'x2', 'x3']
print('C matrix \n', np.vstack(C))
print('x unknowns \n', x)
print('Cx = v vector\n',np.vstack(v))
print('The inverse of C matrix \n', inv(C))
print('The inversion solution \n', list(zip(x,np.dot(inv(C), v))))

C matrix 
 [[ 4  3 -5]
 [-2 -4  5]
 [ 8  8  0]]
x unknowns 
 ['x1', 'x2', 'x3']
Cx = v vector
 [[ 2]
 [ 5]
 [-3]]
The inverse of C matrix 
 [[ 0.33333333  0.33333333  0.04166667]
 [-0.33333333 -0.33333333  0.08333333]
 [-0.13333333  0.06666667  0.08333333]]
The inversion solution 
 [('x1', 2.208333333333333), ('x2', -2.583333333333333), ('x3', -0.18333333333333335)]


In [104]:
A = np.array([[5, 3, -5], 
              [-2, -1, 5], 
              [8, 8, -1]])
y = np.array([2, 5, -3])

x = np.linalg.solve(A, y)
print('numpy soultion function \n', x)
A_inv = np.linalg.inv(A)

x1 = np.dot(A_inv, y)
print('The inversion solution \n', x1)

numpy soultion function 
 [ 7.14634146 -7.2195122   2.41463415]
The inversion solution 
 [ 7.14634146 -7.2195122   2.41463415]


In [109]:
from scipy.linalg import lu

P, L, U = lu(A)
print('A:\n', A)
print('P:\n', P)
print('L:\n', L)
print('U:\n', U)
print('LU:\n',np.dot(L, U))
print('PdotA:\n', np.dot(P, A))

A:
 [[ 5  3 -5]
 [-2 -1  5]
 [ 8  8 -1]]
P:
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L:
 [[ 1.     0.     0.   ]
 [ 0.625  1.     0.   ]
 [-0.25  -0.5    1.   ]]
U:
 [[ 8.      8.     -1.    ]
 [ 0.     -2.     -4.375 ]
 [ 0.      0.      2.5625]]
LU:
 [[ 8.  8. -1.]
 [ 5.  3. -5.]
 [-2. -1.  5.]]
PdotA:
 [[-2. -1.  5.]
 [ 8.  8. -1.]
 [ 5.  3. -5.]]


In [121]:
from scipy.linalg import lu

A = np.random.randint(0, 10,(4, 4))

P,L,U = lu(A) # if true the multiplication P*L (Default: do not permute) 
print('P:\n', P)
print('invP:\n', inv(P))
print('L:\n', L)
print('U:\n', U)

PL = np.dot(P,L) # permute the lower triangular with unit diagonal elements
print("""
LU factorization is a way of decomposing a matrix A into an
upper triangular matrix U , a lower triangular matrix L ,
and a permutation matrix P such that PA = LU or A = P^-1LU or PLU
and A^-1 = (PL^-1)U^-1,
where the inverse permutation matrix P =  permutation matrix P""")
print('PL:\n', U)
PL_inv = np.linalg.inv(PL)
print('invPL:\n', PL_inv)
U_inv = np.linalg.inv(U)
print('invU:\n', U_inv)
A_inv = np.dot(U_inv,PL_inv)
print('invA from UL:\n', A_inv)
print('inv(A) function:\n',np.linalg.inv(A))
print("""
Now that we have the lower (l) and upper (u) triangular matrices,
we can find the inverse of A by the following equation : A^-1 = U^-1 L^-1
the inverse of A = inverse of U x inverse L""")

P:
 [[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]
invP:
 [[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]
L:
 [[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 0.125       0.28571429  1.          0.        ]
 [ 0.5         0.14285714 -0.35335689  1.        ]]
U:
 [[ 8.          8.          3.          8.        ]
 [ 0.          7.          9.          9.        ]
 [ 0.          0.          5.05357143 -1.57142857]
 [ 0.          0.          0.          0.1590106 ]]

LU factorization is a way of decomposing a matrix A into an
upper triangular matrix U , a lower triangular matrix L ,
and a permutation matrix P such that PA = LU or A = P^-1LU or PLU
and A^-1 = (PL^-1)U^-1,
where the inverse permutation matrix P =  permutation matrix P
PL:
 [[ 8.          8.          3.          8.        ]
 [ 0.          7.          9.          9.        ]
 [ 0.          0.          5.05357143 -1.57142857]
 [ 0.          0.  

In [1]:
print(a= EX2)
u = np.array([[1], [0.001]])
tol = 0.01
v = np.array([[1], [1]])
ut = u.T
th = np.arccos(np.dot(ut, v)/(norm(u)*norm(v)))
if (np.pi/2 - th) < tol:
    print(1)
else:
    print(0)

NameError: name 'EX2' is not defined

In [14]:
import numpy as np
from numpy.linalg import inv
A = [[0, 1, 0], [0, 0, 2]]
A
p = np.array([1, 0, 2])
p.T

array([1, 0, 2])

In [6]:
r2 = np.multiply(A, [2,0,1])
r2

array([[0, 0, 0],
       [0, 0, 2]])

In [11]:
p.inv

AttributeError: 'list' object has no attribute 'inv'