In [4]:
import numpy as np
x = np.array([0, 1, 2])
y = np.array([1, 3, 2])

n = len(x)
num = 4*(n-1)
yo = [0]*num
for i in range(int(num/2/2)):
    yo[i] = y[i]
    yo[i+2] = y[i+1]
yo = np.array(yo)
co = np.zeros((num, num))
for j in range(0, 1):
    for i in range(0, 4):
        r1 = x[j]**(i+1)
        co[j, i] = r1
        if i == 3:
            co[j,i] = 1
for j in range(1, 2):
    for i in range(4, 8):
        r1 = x[j]**(i+1) 
        co[j, i] = r1
        if i == 7:
            co[j,i] = 1
for j in range(2, 3):
    for i in range(0, 4):
        r1 = x[j-1]**(i+1)
        co[j, i] = r1
        if i == 3:
            co[j,i] = 1
for j in range(3, 4):
    for i in range(4, 8):
        r1 = x[j-1]**(7-i)
        co[j, i] = r1
        if i == 7:
            co[j,i] = 1
for j in range(4, 5):
    for i in range(0, 4):
        r1 = (3-i)*x[j-3]**(3-i)
        co[j, i] = r1
        if i == 2:
            co[j,i] = 1
    for i in range(4, 8):
        r1 = -(7-i)*x[j-3]**(7-i)
        co[j, i] = r1
for j in range(5, 6):
    for i in range(0, 2):
        r1 = 6*x[j-4]
        co[j, i] = r1
        if i == 1:
            co[j,i] = 2
    for i in range(4, 6):
        r1 = -6*x[j-4]
        co[j, i] = r1
        if i == 5:
            co[j,i] = -2
for j in range(6, 7):
    for i in range(0, 2):
        r1 = 6*x[j-6]
        r2 = 6*x[j-4]
        co[j, i] = r1
        co[j+1, i+4] = r2
        if i == 1:
            co[j,i] = 2
            co[j+1,i+4] = 2
print(co)
print(yo)
coef = np.dot(np.linalg.inv(co), yo)

[[ 0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  8.  4.  2.  1.]
 [ 3.  2.  1.  0. -3. -2. -1.  0.]
 [ 6.  2.  0.  0. -6. -2.  0.  0.]
 [ 0.  2.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0. 12.  2.  0.  0.]]
[1 3 3 2 0 0 0 0]


In [5]:
coef

array([-0.75,  0.  ,  2.75,  1.  ,  0.75, -4.5 ,  7.25, -0.5 ])

In [160]:
co

array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  8.,  4.,  2.,  1.],
       [ 3.,  2.,  1.,  0., -3., -2., -1.,  0.],
       [ 6.,  2.,  0.,  0., -6.,  2.,  0.,  0.],
       [ 0.,  2.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  6.,  2.,  0.,  0.]])