# 2.8.2 Problems Python Programming and Numerical Methods

In [395]:
import numpy as np
import pandas as pd
from math import*
import re

try:
    y = x1**2
except Exception as e:
    print('Create the error code; NameError:', e)

x, y = 2, 3
print(f'Assign x and y, x = {x} and y = {y}\n')

S = '123'
N = float(S)
print('S is of number type',type(S), S)
print('N is of number type',type(N), N, '\n')

Create the error code; NameError: name 'x1' is not defined
Assign x and y, x = 2 and y = 3

S is of number type <class 'str'> 123
N is of number type <class 'float'> 123.0 



In [375]:


def assignments(x, y):
    u = x + y
    v = x * y
    w = x / y
    z = sin(x)
    r = 8 * sin(x)
    s = 5 * sin(x*y)
    p = x**y
    return [u, v, w, z, r, s, p]


ass_lst = ['u', 'v', 'w', 'z', 'r', 's', 'p']
opr_lst = np.around(assignments(10, 3), 3)

df_ass = pd.DataFrame({'Variables': ass_lst, 'Values':  opr_lst},
                  index=('x + y', 'xy', 'x/y', 'sin(x)', '8sin(x)', '5sin(xy)', 'x**y'),
                  columns=['Variables', 'Values'])
df_ass.index.name = "Expressions" 
print('Showing all variables and values from the given expressions.')
print(df_ass,'\n')

Showing all variables and values from the given expressions.
            Variables    Values
Expressions                    
x + y               u    13.000
xy                  v    30.000
x/y                 w     3.333
sin(x)              z    -0.544
8sin(x)             r    -4.352
5sin(xy)            s    -4.940
x**y                p  1000.000 



In [376]:
s1 = 'HELLO'
s2 = 'hello'
print(f'The upper case {s1} and lower case {s2} words are not equal; is {s1} equal to {s2}, {s1 == s2}')
print(f'Putting {s1} to lower case {s1.lower()} the words are then equal; is {s1.lower()} equal to {s2}, {s1.lower() == s2}')
print(f'Changing {s2} to upper case {s2.upper()} the words are then equal; is {s2.upper()} equal to {s1}, {s1 == s2.upper()}\n')

The upper case HELLO and lower case hello words are not equal; is HELLO equal to hello, False
Putting HELLO to lower case hello the words are then equal; is hello equal to hello, True
Changing hello to upper case HELLO the words are then equal; is HELLO equal to HELLO, True



In [377]:
w_1 = int(len('Engineering'))
w_lst = list('Engineering')
w_2 = int(len('Book'))
w_2st = list('Book')
tot = w_1 + w_2
print(f'The count of the letter in Engineering ({w_lst}) is {w_1} and the letter count in Book ({w_2st}) is {w_2} '
      f'and total letter count is {tot}.\n')

The count of the letter in Engineering (['E', 'n', 'g', 'i', 'n', 'e', 'e', 'r', 'i', 'n', 'g']) is 11 and the letter count in Book (['B', 'o', 'o', 'k']) is 4 and total letter count is 15.



In [378]:
words = 'Python is Great'

word1 = re.search(r"(^\w+)", words) # Start the match at the begainning ^ matching all charaters\w+ until a space
word2 = re.search(r"(\w+)$", words) # Start the match at the end $ matching all charaters\w+ until a space
print(f'Using the re.match exact pattern, the word Python was found in "{words}"')
print(word1.group(0),'\n') # Group zero which means every thing in all groups.
print(f'Using a general regex pattern a search for the last word was completed,'
      f'the last word Great was found in "{words}"')
print(word2.group(0),'\n')

Using the re.match exact pattern, the word Python was found in "Python is Great"
Python 

Using a general regex pattern a search for the last word was completed,the last word Great was found in "Python is Great"
Great 



In [379]:
list_a = [1, 8, 9, 15]
print(f'The orginal list is: {list_a}.')
list_a[1] = 2
print(f'Insert 2 at index number 1 in orginal list: {list_a}.')
list_a.append(4)
print(f'Append the orginal list with a 4: {list_a}.')
list_a.sort()
print(f'This is the sort list: {list_a}.\n')

The orginal list is: [1, 8, 9, 15].
Insert 2 at index number 1 in orginal list: [1, 2, 9, 15].
Append the orginal list with a 4: [1, 2, 9, 15, 4].
This is the sort list: [1, 2, 4, 9, 15].



In [380]:
words_list = list(words)
print(f'This is a list of, "{words}".')
print(words_list, '\n')

This is a list of, "Python is Great".
['P', 'y', 't', 'h', 'o', 'n', ' ', 'i', 's', ' ', 'G', 'r', 'e', 'a', 't'] 



In [381]:
tuple_a = ('One', 1)
print(f'This is the variables assiged to tuple_a {tuple_a}.')
print('Get the second element in tuple_a', tuple_a[1:3], '\n')

This is the variables assiged to tuple_a ('One', 1).
Get the second element in tuple_a (1,) 



In [382]:
set_o = {2, 3, 2, 3, 1, 2, 5}
print('Unique elements of (2, 3, 2, 3, 1, 2, 5) are:', set_o)
set_a = {2, 3, 2}
set_b = {1, 2, 3}
set_c = {11, 2, 8}
set_u = set_a.union(set_b)
print('The union of (2, 3, 2) and (1, 2, 3) is:', set_u)
set_i = set_a.intersection(set_b)
print('The intersection of (2, 3, 2) and (1, 2, 3) is:', set_i)
set_s = set_a.issubset(set_b)
print('Is (2, 3, 2) a sub set of (1, 2, 3)?', set_s)
set_d = set_c.difference(set_a)
print('The difference between  (11, 3, 8) and (2, 3, 2) is:', set_d, '\n')

Unique elements of (2, 3, 2, 3, 1, 2, 5) are: {1, 2, 3, 5}
The union of (2, 3, 2) and (1, 2, 3) is: {1, 2, 3}
The intersection of (2, 3, 2) and (1, 2, 3) is: {2, 3}
Is (2, 3, 2) a sub set of (1, 2, 3)? True
The difference between  (11, 3, 8) and (2, 3, 2) is: {8, 11} 



In [383]:
keys = ['A', 'B', 'C']
val = ['a', 'b', 'c']
dict_1 = dict(zip(keys, val))
dict_keys = dict_1.keys()

print(f'The keys for the dictionary {dict_1} are {keys}.')
print(f'The value of key "B" is:', dict_1['B'], '\n')

The keys for the dictionary {'A': 'a', 'B': 'b', 'C': 'c'} are ['A', 'B', 'C'].
The value of key "B" is: b 



In [384]:
x = np.array([1, 4, 3, 2, 9, 4])
y = np.array([2, 3, 4, 1, 2, 3])


def assignments(x, y):
    u = np.add(x, y)
    v = np.multiply(x, y)
    w = np.divide(x, y)
    z = np.sin(x)
    r = 8 * np.sin(x)
    s = 5 * np.sin(np.multiply(x, y))
    p = np.power(x, y)
    return [u, v, w, z, r, s, p]

ass_lst = ['u', 'v', 'w', 'z', 'r', 's', 'p']
opr_lst = np.around(assignments(x, y), 3)
opr_lst = list(opr_lst)
df_ass = pd.DataFrame({'Arrays': ass_lst, 'Array Values':  opr_lst},
                  index=('x + y', 'xy', 'x/y', 'sin(x)', '8sin(x)', '5sin(xy)', 'x**y'),
                  columns=['Arrays', 'Array Values'])
df_ass.index.name = "Expressions" 
print('Showing all variables and values from the given expressions.')
print(f'Where x is an array of {x} and y is an array of {y}')
print(df_ass,'\n')

Showing all variables and values from the given expressions.
Where x is an array of [1 4 3 2 9 4] and y is an array of [2 3 4 1 2 3]
            Arrays                                    Array Values
Expressions                                                       
x + y            u                 [3.0, 7.0, 7.0, 3.0, 11.0, 7.0]
xy               v              [2.0, 12.0, 12.0, 2.0, 18.0, 12.0]
x/y              w             [0.5, 1.333, 0.75, 2.0, 4.5, 1.333]
sin(x)           z    [0.841, -0.757, 0.141, 0.909, 0.412, -0.757]
8sin(x)          r    [6.732, -6.054, 1.129, 7.274, 3.297, -6.054]
5sin(xy)         s  [4.546, -2.683, -2.683, 4.546, -3.755, -2.683]
x**y             p              [1.0, 64.0, 81.0, 2.0, 81.0, 64.0] 



In [385]:
arr_100 = np.linspace(-10,10,100)
arr_100 = np.around(arr_100, 5)
print(f'This is an array of 100 numbers that are evenly spaced between -10 and 10.\n {arr_100}')
print('The number of elemnets in the array is:', arr_100.shape, '\n')

This is an array of 100 numbers that are evenly spaced between -10 and 10.
 [-10.       -9.79798  -9.59596  -9.39394  -9.19192  -8.9899   -8.78788
  -8.58586  -8.38384  -8.18182  -7.9798   -7.77778  -7.57576  -7.37374
  -7.17172  -6.9697   -6.76768  -6.56566  -6.36364  -6.16162  -5.9596
  -5.75758  -5.55556  -5.35354  -5.15152  -4.94949  -4.74747  -4.54545
  -4.34343  -4.14141  -3.93939  -3.73737  -3.53535  -3.33333  -3.13131
  -2.92929  -2.72727  -2.52525  -2.32323  -2.12121  -1.91919  -1.71717
  -1.51515  -1.31313  -1.11111  -0.90909  -0.70707  -0.50505  -0.30303
  -0.10101   0.10101   0.30303   0.50505   0.70707   0.90909   1.11111
   1.31313   1.51515   1.71717   1.91919   2.12121   2.32323   2.52525
   2.72727   2.92929   3.13131   3.33333   3.53535   3.73737   3.93939
   4.14141   4.34343   4.54545   4.74747   4.94949   5.15152   5.35354
   5.55556   5.75758   5.9596    6.16162   6.36364   6.56566   6.76768
   6.9697    7.17172   7.37374   7.57576   7.77778   7.9798    8.18182
  

In [386]:
array_a = np.array([-1, 0, 1, 2, 0, 3])
print(f'All elements that are greater than 0.0 in {array_a} are {array_a[array_a > 0]}.')

All elements that are greater than 0.0 in [-1  0  1  2  0  3] are [1 2 3].


In [387]:
array_y = np.array([[3, 5, 3], [2, 2, 5], [3, 8, 9]])
print(f'The orginal 3x3 matrix \n {array_y}')
print(f'The transposed 3x3 matrix \n {array_y.T}\n')

The orginal 3x3 matrix 
 [[3 5 3]
 [2 2 5]
 [3 8 9]]
The transposed 3x3 matrix 
 [[3 2 3]
 [5 2 8]
 [3 5 9]]



In [388]:
dim = (2, 4)
array_24 = np.zeros(dim)
print(f'This is a 2x4 zero array\n {array_24}.\n')
array_24[:,1] = 1.0
print(f'The zero array column 1 was changed to 1.0\n {array_24}\n')

This is a 2x4 zero array
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]].

The zero array column 1 was changed to 1.0
 [[0. 1. 0. 0.]
 [0. 1. 0. 0.]]



In [389]:
all_var = %who
print('This is all the variables used in chapter 2 problems')
print(all_var)
%reset
print("This is what what remained after the varible reset.")
all_var = %who
print(all_var)

acos	 acosh	 all_var	 arr_100	 array_24	 array_a	 array_y	 asin	 asinh	 
ass_lst	 assignments	 atan	 atan2	 atanh	 ceil	 comb	 copysign	 cos	 
cosh	 degrees	 df_ass	 dict_1	 dict_keys	 dim	 dist	 erf	 erfc	 
exp	 expm1	 fabs	 factorial	 floor	 fmod	 frexp	 fsum	 gamma	 
gcd	 hypot	 inf	 isclose	 isfinite	 isinf	 isnan	 isqrt	 keys	 
lcm	 ldexp	 lgamma	 list_a	 log	 log10	 log1p	 log2	 modf	 
nan	 nextafter	 np	 opr_lst	 pd	 perm	 pi	 pow	 prod	 
radians	 re	 remainder	 s1	 s2	 set_a	 set_b	 set_c	 set_d	 
set_i	 set_o	 set_s	 set_u	 sin	 sinh	 sqrt	 tan	 tanh	 
tau	 tot	 trunc	 tuple_a	 ulp	 val	 w_1	 w_2	 w_2st	 
w_lst	 word1	 word2	 words	 words_list	 x	 y	 
This is all the variables used in chapter 2 problems
None
Once deleted, variables cannot be recovered. Proceed (y/[n])? n
Nothing done.
This is what what remained after the varible reset.
acos	 acosh	 all_var	 arr_100	 array_24	 array_a	 array_y	 asin	 asinh	 
ass_lst	 assignments	 atan	 atan2	 atanh	 ceil	 comb	 copysign	 cos	 
